// VeilBreakers Auto-Generated: UI Sound Manager (AU-01)
// Runtime UI sound infrastructure for dark fantasy menus
using UnityEngine;
using UnityEngine.Audio;
using System.Collections.Generic;

namespace VeilBreakers.Audio
{
/// <summary>
/// UI sound types covering all common menu interactions.
/// Dark fantasy audio feel: deep clicks, metallic slides, chain rattles.
/// </summary>
public enum UISoundType
{
    ButtonHover,
    ButtonClick,
    ButtonBack,
    TabSwitch,
    SliderChange,
    ToggleOn,
    ToggleOff,
    InventoryOpen,
    InventoryClose,
    ItemPickup,
    ItemDrop,
    ItemEquip,
    ItemUnequip,
    ItemSell,
    ItemBuy,
    SkillUnlock,
    QuestAccept,
    QuestComplete,
    NotificationPopup,
    MenuOpen,
    MenuClose,
    MapOpen,
    MapClose,
    LevelUp,
    Error,
    Confirm,
    Cancel
}

/// <summary>
/// Serializable mapping from a UISoundType to an array of AudioClips.
/// Multiple clips per type enables random variety on each play.
/// </summary>
[System.Serializable]
public class UISoundEntry
{
    public UISoundType soundType;
    [Tooltip("Multiple clips for random variety per play")]
    public AudioClip[] clips;
    [Range(0f, 1f)]
    [Tooltip("Volume multiplier for this sound type")]
    public float volumeScale = 1.0f;
    [Tooltip("Minimum pitch (default 0.95 for subtle variation)")]
    public float minPitch = 0.95f;
    [Tooltip("Maximum pitch (default 1.05 for subtle variation)")]
    public float maxPitch = 1.05f;
    [Tooltip("Cooldown in seconds to prevent spam")]
    public float cooldown = 0.05f;
}

/// <summary>
/// Singleton UI sound manager with DontDestroyOnLoad.
/// Plays UI sounds with per-type clip arrays, pitch randomization,
/// per-type cooldown, independent volume via AudioMixerGroup, and
/// an AudioSource pool for overlapping sounds.
///
/// Usage:
///   VB_UISoundManager.Instance.PlayUISound(UISoundType.ButtonClick);
///
/// Generated by VeilBreakers MCP toolkit.
/// </summary>
[DisallowMultipleComponent]
public class VB_UISoundManager : MonoBehaviour
{
    [Header("Sound Configuration")]
    [Tooltip("Map each UISoundType to one or more AudioClips")]
    [SerializeField] private UISoundEntry[] soundEntries;

    [Header("Audio Mixer")]
    [Tooltip("Assign the UI mixer group for independent volume control")]
    [SerializeField] private AudioMixerGroup uiMixerGroup;

    [Header("Pool Settings")]
    [Tooltip("Number of AudioSources for overlapping UI sounds")]
    [SerializeField] private int poolSize = 3;

    [Header("Global Settings")]
    [Range(0f, 1f)]
    [SerializeField] private float masterUIVolume = 1.0f;

    private static VB_UISoundManager _instance;
    public static VB_UISoundManager Instance => _instance; // VB-IGNORE UNITY-15 -- [DisallowMultipleComponent] on class

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetStatics()
    {
        _instance = default;
    }

    private AudioSource[] _sourcePool;
    private int _nextSourceIndex;
    private Dictionary<UISoundType, UISoundEntry> _soundMap;
    private Dictionary<UISoundType, float> _lastPlayTime;

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
            return;
        }
        _instance = this;
        DontDestroyOnLoad(gameObject);

        InitializePool();
        BuildSoundMap();
    }

    private void InitializePool()
    {
        _sourcePool = new AudioSource[poolSize];
        for (int i = 0; i < poolSize; i++)
        {
            GameObject child = new GameObject("VB_UIAudio_" + i);
            child.transform.SetParent(transform);
            AudioSource src = child.AddComponent<AudioSource>();
            src.playOnAwake = false;
            src.spatialBlend = 0.0f; // 2D for UI
            src.loop = false;
            if (uiMixerGroup != null)
                src.outputAudioMixerGroup = uiMixerGroup;
            _sourcePool[i] = src;
        }
        _nextSourceIndex = 0;
    }

    private void BuildSoundMap()
    {
        _soundMap = new Dictionary<UISoundType, UISoundEntry>();
        _lastPlayTime = new Dictionary<UISoundType, float>();

        if (soundEntries == null) return;

        foreach (UISoundEntry entry in soundEntries)
        {
            _soundMap[entry.soundType] = entry;
            _lastPlayTime[entry.soundType] = -999f;
        }
    }

    /// <summary>
    /// Play a UI sound by type. Selects a random clip from the configured
    /// array, applies pitch variation, respects cooldown, and uses the
    /// next available pooled AudioSource.
    /// </summary>
    /// <param name="type">The UI sound type to play.</param>
    public void PlayUISound(UISoundType type)
    {
        if (_soundMap == null || !_soundMap.TryGetValue(type, out UISoundEntry entry))
            return;

        if (entry.clips == null || entry.clips.Length == 0)
            return;

        // Cooldown check
        if (_lastPlayTime.TryGetValue(type, out float lastTime))
        {
            if (Time.unscaledTime - lastTime < entry.cooldown)
                return;
        }
        _lastPlayTime[type] = Time.unscaledTime;

        // Select random clip for variety
        AudioClip clip = entry.clips[Random.Range(0, entry.clips.Length)];
        if (clip == null) return;

        // Get next pooled source (round-robin)
        AudioSource source = GetNextSource();

        // Apply settings
        source.clip = clip;
        source.volume = masterUIVolume * entry.volumeScale;
        source.pitch = Random.Range(entry.minPitch, entry.maxPitch);

        // Ensure mixer group is assigned
        if (uiMixerGroup != null)
            source.outputAudioMixerGroup = uiMixerGroup;

        source.Play();
    }

    /// <summary>
    /// Play a UI sound with a specific volume override.
    /// </summary>
    /// <param name="type">The UI sound type to play.</param>
    /// <param name="volumeOverride">Volume override (0-1), multiplied by masterUIVolume.</param>
    public void PlayUISound(UISoundType type, float volumeOverride)
    {
        if (_soundMap == null || !_soundMap.TryGetValue(type, out UISoundEntry entry))
            return;

        if (entry.clips == null || entry.clips.Length == 0)
            return;

        // Cooldown check
        if (_lastPlayTime.TryGetValue(type, out float lastTime))
        {
            if (Time.unscaledTime - lastTime < entry.cooldown)
                return;
        }
        _lastPlayTime[type] = Time.unscaledTime;

        AudioClip clip = entry.clips[Random.Range(0, entry.clips.Length)];
        if (clip == null) return;

        AudioSource source = GetNextSource();
        source.clip = clip;
        source.volume = masterUIVolume * volumeOverride;
        source.pitch = Random.Range(entry.minPitch, entry.maxPitch);

        if (uiMixerGroup != null)
            source.outputAudioMixerGroup = uiMixerGroup;

        source.Play();
    }

    /// <summary>
    /// Set the master UI volume (0-1). Independent from SFX volume.
    /// </summary>
    public void SetMasterUIVolume(float volume)
    {
        masterUIVolume = Mathf.Clamp01(volume);
    }

    /// <summary>
    /// Get the current master UI volume.
    /// </summary>
    public float GetMasterUIVolume()
    {
        return masterUIVolume;
    }

    /// <summary>
    /// Update the mixer group at runtime (e.g., after loading AudioMixer).
    /// </summary>
    public void SetMixerGroup(AudioMixerGroup group)
    {
        uiMixerGroup = group;
        if (_sourcePool != null)
        {
            foreach (AudioSource src in _sourcePool)
            {
                if (src != null)
                    src.outputAudioMixerGroup = group;
            }
        }
    }

    /// <summary>
    /// Returns whether a specific sound type has been configured with clips.
    /// </summary>
    public bool HasSound(UISoundType type)
    {
        if (_soundMap == null) return false;
        if (!_soundMap.TryGetValue(type, out UISoundEntry entry)) return false;
        return entry.clips != null && entry.clips.Length > 0;
    }

    /// <summary>
    /// Returns the number of configured sound types.
    /// </summary>
    public int ConfiguredSoundCount
    {
        get { return _soundMap != null ? _soundMap.Count : 0; }
    }

    private AudioSource GetNextSource()
    {
        // Prefer non-playing source first
        for (int i = 0; i < _sourcePool.Length; i++)
        {
            int idx = (_nextSourceIndex + i) % _sourcePool.Length;
            if (!_sourcePool[idx].isPlaying)
            {
                _nextSourceIndex = (idx + 1) % _sourcePool.Length;
                return _sourcePool[idx];
            }
        }
        // All playing -- round-robin recycle
        AudioSource recycled = _sourcePool[_nextSourceIndex];
        _nextSourceIndex = (_nextSourceIndex + 1) % _sourcePool.Length;
        recycled.Stop();
        return recycled;
    }
}
}
